```{r}
# Necessary libraries
library(CellChat)
library(Seurat)
library(patchwork)
options(stringsAsFactors = FALSE)
```

```{r}
# Specify directory
data_dir <- "G:/My Drive/Projects/Yi's scRNA Data/Data/Processed"
current <- getwd()
```

```{r}
# Data Import
setwd(data_dir)
load("allsamples_PCA_cluster_dims20_res0.5.Rd")
data <- allsamples_PCA_cluster_dims20_res0.5
setwd(current)
```

```{r}
# Create CellChat object
data$cluster <- data@active.ident
cellchat <-
createCellChat(object = data, assay = "RNA", group.by = "cluster")
```

```{r}
# Load and Select Database
cellchat_db <- CellChatDB.human
# Choose molecular interaction type
cellchat_db_use <- subsetDB(cellchat_db, search = "Secreted Signaling")
cellchat@DB <- cellchat_db_use
```

```{r}
# Preprocessing
cellchat <-
subsetData(cellchat) # This step is necessary even if using the whole database
future::plan("multiprocess", workers = 8) # do parallel
cellchat <- identifyOverExpressedGenes(cellchat)
cellchat <- identifyOverExpressedInteractions(cellchat)
# project gene expression data onto PPI network (optional)
cellchat <- projectData(cellchat, PPI.human)
```

```{r}
# Infer cell-cell communication network
cellchat <- computeCommunProb(cellchat, type = "truncatedMean", trim = 0.05)
# Filter out the cell-cell communication if there are only few cells
cellchat <- filterCommunication(cellchat, min.cells = 5)
# Calculate communication at signaling pathway level
cellchat <- computeCommunProbPathway(cellchat)
# Calculate aggregated cell-cell communication network
cellchat <- aggregateNet(cellchat)
```

```{r}
# Save data file processed thus far to .RDS
setwd(data_dir)
saveRDS(cellchat, file = "cellchat_processed.rds")
setwd(current)
```








```{r}
# Read saved .RDS
setwd(data_dir)
cellchat <- readRDS("cellchat_processed.rds")
setwd(current)
```

```{r}
# Visualize aggregate communication network
group_size <- as.numeric(table(cellchat@idents))
par(mfrow = c(1, 2), xpd = TRUE)
netVisual_circle(cellchat@net$count, vertex.weight = group_size,
weight.scale = T, label.edge = F, title.name = "Number of interactions")
netVisual_circle(cellchat@net$weight, vertex.weight = group_size,
weight.scale = T, label.edge = F, title.name = "Interaction weights/strength")
```

```{r}
# Visualize aggregate communication network by cluster
mat <- cellchat@net$weight
par(mfrow = c(2, 4), xpd = TRUE)
for (i in seq_len(nrow(mat))) {
  mat2 <- matrix(0, nrow = nrow(mat), ncol = ncol(mat),
  dimnames = dimnames(mat))
  mat2[i, ] <- mat[i, ]
  netVisual_circle(mat2, vertex.weight = group_size, weight.scale = T,
  edge.weight.max = max(mat), title.name = rownames(mat)[i])
}
```

```{r}
# show calculated pathways
cellchat@netP$pathways
```

```{r}
# Specific pathway outputs
pathways_show <- c("WNT")
# Export configuration
pathways_filename <- paste(pathways_show, ".pdf", sep = "")
pdf(pathways_filename, paper = "letter", width = 8, height = 8)
# Hierachy plot
vertex_receiver <- seq(1, 4) # a numeric vector
netVisual_aggregate(cellchat, signaling = pathways_show,
vertex.receiver = vertex_receiver)
# Heatmap (using pathway from above chunk)
par(mfrow = c(1, 1))
netVisual_heatmap(cellchat, signaling = pathways_show, color.heatmap = "Reds")
dev.off()
```

```{r}
pathways_show <- c("WNT")
# Pathway ligand-receptor pair strength
pdf("WNT_LR_pair_strength.pdf", width = 8, height = 20)
netAnalysis_contribution(cellchat, signaling = pathways_show)
dev.off()
```

```{r}
pair_show <- c("WNT6_FZD3_LRP6") # show one ligand-receptor pair
# LR-specific Hierarchy plot
vertex_receiver <- seq(1, 4) # a numeric vector
netVisual_individual(
cellchat, signaling = pathways_show, pairLR.use = pair_show,
vertex.receiver = vertex_receiver)
```

```{r}
# Compute the network centrality scores
cellchat <- netAnalysis_computeCentrality(cellchat, slot.name = "netP")
# Identify signal contributions in each cluster
pdf("Signal_contribution.pdf", width = 8.5, height = 11)
netAnalysis_signalingRole_heatmap(cellchat, pattern = "outgoing",
width = 11, height = 20)
netAnalysis_signalingRole_heatmap(cellchat, pattern = "incoming",
width = 11, height = 20)
dev.off()
```









```{r}
```
