Following Seurat tutorials:
https://satijalab.org/seurat/v3.2/pbmc3k_tutorial.html
https://satijalab.org/seurat/v3.2/integration.html


---
title: "R Notebook"
output: html_notebook
---

```{r}

rm(list = ls()) # clear the environment 

library(Seurat)
library(cowplot)
library(ggplot2)
library(cowplot)
library(patchwork)

library(dplyr)

library(ggpubr)
library(RColorBrewer)

library(magick)

# Data Import
current <- getwd()
setwd("G:/My Drive/Projects/Yi's scRNA Data/Data/Processed")
load('allsamples_PCA_cluster_dims20_res0.5.Rd')
setwd(current)


```


```{r}

##3D diffusion
## Trajectory by Diffusion map  https://bioconductor.org/packages/release/bioc/html/destiny.html
library(destiny)



cell_cluster_id=as.character(Idents(allsamples_PCA_cluster_dims20_res0.5))

# Using the PCA stored within Seurat object to build diffusion map
pca=Embeddings(allsamples_PCA_cluster_dims20_res0.5,reduction='pca')
dm=DiffusionMap(pca)

# Create pseudotime ordering and assigns cell to one of three branches
# choose the 10th cell (a cell in cluster 3) as the root
dpt=DPT(dm)

#ref for the colors of clusters:
#new.cluster.ids <- c("ESC","PSLCs","MeLC1","MeLC2","NasAMLC",  "AMLC1", "AMLC2","PGCLCs")
#color<-c('#D39200','#00C19F','#F8766D','#DB72FB','#619CFF','#93AA00','#00B9E3','#00BA38')
#NewOrder = c(3, 1, 5, 0, 4, 6, 7, 2)

#plot 3D diffusion map for all cells
library(rgl)

df1=data.frame(DC1 = eigenvectors(dm)[, 1], DC2 = eigenvectors(dm)[, 2], DC3 = eigenvectors(dm)[, 3],dptval = dpt$dpt, cell_type = cell_cluster_id)


#df2 for plotting, cell type is replaced be color code
df2<-df1

df2[df2=="ESC"]<-"#D39200"
df2[df2=="PSLCs"]<-"#00C19F"
df2[df2=="MeLC1"]<-"#F8766D"
df2[df2=="MeLC2"]<-"#DB72FB"
df2[df2=="NasAMLC"]<-"#619CFF"
df2[df2=="AMLC1"]<-"#93AA00"
df2[df2=="AMLC2"]<-"#00B9E3"
df2[df2=="PGCLCs"]<-"#00BA38"

#new.cluster.ids <- c("ESC","PSLCs","MeLC1","MeLC2","NasAMLC",  "AMLC1", "AMLC2","PGCLCs")
#color<-c('#D39200','#00C19F','#F8766D','#DB72FB','#619CFF','#93AA00','#00B9E3','#00BA38')

#plot 3D map and change views
plot3d(df2, x = df1$DC1, y = df1$DC3, z = df1$DC2,
xlab = "DC1", ylab = "DC3", zlab = "DC2",
type = "p", radius = .0001, size = 2, col = df2$cell_type)

view3d(theta = 0, phi = 90, zoom = 0.6)

# Preview
play3d(spin3d(axis = c(0, 0, 1)), duration = 10)

# Make gif
movie3d(spin3d(axis = c(0, 0, 1)), duration = 10, dir = current,
movie = "diffusion_3d", convert = TRUE, clean = FALSE, fps = 30)

#output pdf file
# rgl.postscript("plot3d.pdf", "pdf", drawText = FALSE)

```



```{r}
# #2D plot for all cells
# # plot pseudotime by diffusion components DC1 vs DC2, coloring the cells by diffusion pseudotime value (dptval)
# df=data.frame(DC1 = eigenvectors(dm)[, 1], DC2 = eigenvectors(dm)[, 2], dptval = dpt$dpt, cell_type = cell_cluster_id)
# 
# # If needed, reverse the pseudo time because cluster 7 should be the end, not the start of the differentiation. Alternatively, if the root cell happens to be the left-most point in the map, you can find the index of the cell by running: root_index=which(df$DC1==min(df$DC1)), and then rerun dpt: DPT(dm,tips=root_index)
# 
# df$dptval=max(df$dptval)-df$dptval
# 
# #plot to check the tips points, DPT value 
# plot (dpt)
# plot (dm)
# 
# p1=ggplot(df) + geom_point(aes(x = DC1, y = DC2, color = dptval),size=0.001) + scale_color_gradient2(low='red',mid='green',high='blue',midpoint=1.3) + theme_classic()
# 
# p2=ggplot(df) + geom_point(aes(x = DC1, y = DC2, color = cell_type),size=0.001) + theme_classic() + scale_color_manual(values=c('#93AA00','#00B9E3','#D39200','#F8766D','#DB72FB','#619CFF','#00BA38','#00C19F'))
# 
# pdf(file='All_Diffusion.pdf',width=15,height=6)
# plot_grid(p1, p2)
# dev.off()
```


```{r}
#Using amnion sub clusters

Amnioin_sub<-subset(allsamples_PCA_cluster_dims20_res0.5, idents = c("ESC", "NasAMLC", "AMLC1","AMLC2"))

cell_cluster_id=as.character(Idents(Amnioin_sub))

# Using the PCA stored within Seurat object to build diffusion map
pca=Embeddings(Amnioin_sub,reduction='pca') 
dm=DiffusionMap(pca, )

# Create pseudotime ordering and assigns cell to one of three branches
# choose the 10th cell (a cell in cluster 3) as the root
dpt=DPT(dm)

#ref for the colors of clusters:
#new.cluster.ids <- c("ESC","PSLCs","MeLC1","MeLC2","NasAMLC",  "AMLC1", "AMLC2","PGCLCs")
#color<-c('#D39200','#00C19F','#F8766D','#DB72FB','#619CFF','#93AA00','#00B9E3','#00BA38')
#NewOrder = c(3, 1, 5, 0, 4, 6, 7, 2)


# plot pseudotime by diffusion components DC1 vs DC2, coloring the cells by diffusion pseudotime value (dptval)
df=data.frame(DC1 = eigenvectors(dm)[, 1], DC2 = eigenvectors(dm)[, 2], dptval = dpt$dpt, cell_type = cell_cluster_id)

# If needed, reverse the pseudo time because cluster 7 should be the end, not the start of the differentiation. Alternatively, if the root cell happens to be the left-most point in the map, you can find the index of the cell by running: root_index=which(df$DC1==min(df$DC1)), and then rerun dpt: DPT(dm,tips=root_index)

df$dptval=max(df$dptval)-df$dptval

#plot to check the tips points, DPT value 
# plot (dpt)
# plot (dm)

p1=ggplot(df) + geom_point(aes(x = DC1, y = DC2, color = dptval),size=0.001) + scale_color_gradient2(low='red',mid='green',high='blue',midpoint=1.3) + theme_classic()

p2=ggplot(df) + geom_point(aes(x = DC1, y = DC2, color = cell_type),size=0.001) + theme_classic() + scale_color_manual(values=c('#93AA00','#00B9E3','#D39200','#619CFF'))

pdf(file='Amnioin_sub_Diffusion_try.pdf',width=15,height=6)
plot_grid(p1, p2)
dev.off()


####################################################################################################################
#impose gene expression on the diffusion map
#join with the gene expression matrix stored in the Seurat object
# use RNA, instead of "integrated" to avoid negative value 
df=data.frame(DC1 = eigenvectors(dm)[, 1], DC2 = eigenvectors(dm)[, 2], dptval = dpt$dpt, cell_type = cell_cluster_id, norm_cnt=t(as.matrix(Amnioin_sub@assays$integrated@data)))
# df=data.frame(DC1 = eigenvectors(dm)[, 1], DC2 = eigenvectors(dm)[, 2], dptval = dpt$dpt, cell_type = cell_cluster_id, norm_cnt=t(as.matrix(sub@assays$integrated@data)))

p3=ggplot(df) + geom_point(aes(x = DC1, y = DC2, color = norm_cnt.ISL1),size=0) + theme_classic() + scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdYlBu")))

plot (p3)

pdf(file='Diffusion_pseudotime_ISL1.pdf',width=20,height=6)
plot_grid(p2, p1, p3, cols=3, rows=1)
dev.off()
```


```{r}
#gene expression curves

# If needed, reverse the pseudo time because cluster 7 should be the end, not the start of the differentiation. Alternatively, if the root cell happens to be the left-most point in the map, you can find the index of the cell by running: root_index=which(df$DC1==min(df$DC1)), and then rerun dpt: DPT(dm,tips=root_index)

df=data.frame(DC1 = eigenvectors(dm)[, 1], DC2 = eigenvectors(dm)[, 2], dptval = dpt$dpt, cell_type = cell_cluster_id, norm_cnt=t(as.matrix(Amnioin_sub@assays$integrated@data)))

df$dptval=max(df$dptval)-df$dptval

hist(df$dptval,100)

#filter out dpval with small cell numbers
dff<-df[df$dptval >= 0.075 & df$dptval<= 2, ] 

# # dots, plot loess of dptvalue versus gene expression, use "span" to adjust smoothing, WITH POINTS
# t1=ggplot(df,aes(x=dptval,y=norm_cnt.TFAP2A)) + geom_point(size=0.5,alpha=0.2) + geom_smooth(method = "loess", formula = y ~ x, span=0.1,col='red', se=FALSE) + theme_classic() + xlim (0, 2)


##### no dots

p_list=as.list(1:8)

p_list[[1]]=ggplot(dff, aes(x=dptval,y=norm_cnt.TFAP2A))+geom_smooth(method = "loess", formula = y ~ x, span=0.3, fill="red", colour="darkred", size=0.1) + theme_classic() #+ coord_cartesian(ylim = c(0, 2))

p_list[[2]]=ggplot(dff, aes(x=dptval,y=norm_cnt.GATA3))+geom_smooth(method = "loess", formula = y ~ x, span=0.3, fill="red", colour="darkred", size=0.1) + theme_classic() #+ coord_cartesian(ylim = c(0, 2))

p_list[[3]]=ggplot(dff, aes(x=dptval,y=norm_cnt.ISL1))+geom_smooth(method = "loess", formula = y ~ x, span=0.3, fill="red", colour="darkred", size=0.1) + theme_classic() #+ coord_cartesian(ylim = c(0, 2))

p_list[[4]]=ggplot(dff, aes(x=dptval,y=norm_cnt.MSX2))+geom_smooth(method = "loess", formula = y ~ x, span=0.3, fill="red", colour="darkred", size=0.1) + theme_classic() #+ coord_cartesian(ylim = c(0, 2))

p_list[[5]]=ggplot(dff, aes(x=dptval,y=norm_cnt.TBXT))+geom_smooth(method = "loess", formula = y ~ x, span=0.3, fill="red", colour="darkred", size=0.1) + theme_classic() #+ coord_cartesian(ylim = c(0, 2))



p_list[[6]]=ggplot(dff, aes(x=dptval,y=norm_cnt.GABRP))+geom_smooth(method = "loess", formula = y ~ x, span=0.3, fill="red", colour="darkred", size=0.1) + theme_classic() #+ coord_cartesian(ylim = c(0, 2))

p_list[[7]]=ggplot(dff, aes(x=dptval,y=norm_cnt.ANXA3))+geom_smooth(method = "loess", formula = y ~ x, span=0.3, fill="red", colour="darkred", size=0.1) + theme_classic() #+ coord_cartesian(ylim = c(0, 2))

p_list[[8]]=ggplot(dff, aes(x=dptval,y=norm_cnt.IGFBP3))+geom_smooth(method = "loess", formula = y ~ x, span=0.3, fill="red", colour="darkred", size=0.1) + theme_classic() #+ coord_cartesian(ylim = c(0, 2))



# p_list[[9]]=ggplot(dff, aes(x=dptval,y=norm_cnt.WNT6))+geom_smooth(method = "loess", formula = y ~ x, span=0.3, fill="red", colour="darkred", size=0.1) + theme_classic() #+ coord_cartesian(ylim = c(0, 2))
# 
# p_list[[10]]=ggplot(dff, aes(x=dptval,y=norm_cnt.TCIM))+geom_smooth(method = "loess", formula = y ~ x, span=0.3, fill="red", colour="darkred", size=0.1) + theme_classic()#+ coord_cartesian(ylim = c(0, 2))




#p_NANOG=ggplot(df,aes(x=dptval,y=norm_cnt.NANOG)) + geom_smooth(method = "loess", formula = y ~ x, span=0.3, col='red', se=FALSE) + theme_classic() + xlim (0.075, 1.7) + ylim (0, 2 )

#p_HAND1=ggplot(df,aes(x=dptval,y=norm_cnt.HAND1)) + geom_smooth(method = "loess", formula = y ~ x, span=0.3, col='red', se=FALSE) + theme_classic() + xlim (0.075, 1.7) + ylim (0, 2 )

pdf(file='Amnion_curve_integrated1.pdf',width=7.5,height=3)
ggarrange (plotlist=p_list, ncol = 4, nrow=2)
dev.off()

#plot_grid (p_TFAP2A,p_GATA3,p_ISL1,p_MSX2,p_TBXT,p_WNT6,p_GABRP,p_IGFBP3,p_ANXA3,p_TCIM, cols=2, rows=5)
###########################################################################################################
# # another fitting method
# library(VGAM)
# fit=lm(df$norm_cnt.ISL1 ~ sm.ns(df$dptval, df=3), df) # change df to adjust smoothing
# plot(df$dptval, df$norm_cnt.ISL1, pch=16, col='#33333333', cex=0.5)
# points(df$dptval, fitted(fit), col='red', pch=16, cex=0.5)

# # #plot to verify
# # # change default to RNA to avoid negative value
# DefaultAssay(sub)="RNA"
# 
# # # pdf(file='FeaturePlot.pdf',width=12, height=5)
# # FeaturePlot(object = sub, features = c("ISL1"))
# # # dev.off()
#  
# VlnPlot(object = Amnioin_sub, features = 'ISL1')
# FeaturePlot(object = allsamples_PCA_cluster_dims20_res0.5, features = "ANXA3")

```


```{r}

#Using Meso sub clusters

Meso_sub<-subset(allsamples_PCA_cluster_dims20_res0.5, idents = c("ESC", "PSLCs", "MeLC1","MeLC2"))

cell_cluster_id=as.character(Idents(Meso_sub))

# Using the PCA stored within Seurat object to build diffusion map
pca=Embeddings(Meso_sub,reduction='pca') 
dm=DiffusionMap(pca, )

# Create pseudotime ordering and assigns cell to one of three branches
# choose the 10th cell (a cell in cluster 3) as the root
dpt=DPT(dm)

#ref for the colors of clusters:
#new.cluster.ids <- c("ESC","PSLCs","MeLC1","MeLC2","NasAMLC",  "AMLC1", "AMLC2","PGCLCs")
#color<-c('#D39200','#00C19F','#F8766D','#DB72FB','#619CFF','#93AA00','#00B9E3','#00BA38')
#NewOrder = c(3, 1, 5, 0, 4, 6, 7, 2)


# plot pseudotime by diffusion components DC1 vs DC2, coloring the cells by diffusion pseudotime value (dptval)
df=data.frame(DC1 = eigenvectors(dm)[, 1], DC2 = eigenvectors(dm)[, 2], dptval = dpt$dpt, cell_type = cell_cluster_id)

# If needed, reverse the pseudo time because cluster 7 should be the end, not the start of the differentiation. Alternatively, if the root cell happens to be the left-most point in the map, you can find the index of the cell by running: root_index=which(df$DC1==min(df$DC1)), and then rerun dpt: DPT(dm,tips=root_index)

#df$dptval=max(df$dptval)-df$dptval

#plot to check the tips points, DPT value 
# plot (dpt)
# plot (dm)

p1=ggplot(df) + geom_point(aes(x = DC1, y = DC2, color = dptval),size=0.001) + scale_color_gradient2(low='red',mid='green',high='blue',midpoint=1.3) + theme_classic()
# 
p2=ggplot(df) + geom_point(aes(x = DC1, y = DC2, color = cell_type),size=0.001) + theme_classic() + scale_color_manual(values=c('#93AA00','#F8766D','#DB72FB','#00C19F'))
# 
pdf(file='meso_sub_Diffusion.pdf',width=15,height=6)
plot_grid(p1, p2)
dev.off()


####################################################################################################################
#impose gene expression on the diffusion map
#join with the gene expression matrix stored in the Seurat object
# use RNA, instead of "integrated" to avoid negative value 

df=data.frame(DC1 = eigenvectors(dm)[, 1], DC2 = eigenvectors(dm)[, 2], dptval = dpt$dpt, cell_type = cell_cluster_id, norm_cnt=t(as.matrix(Meso_sub@assays$integrated@data)))

# df=data.frame(DC1 = eigenvectors(dm)[, 1], DC2 = eigenvectors(dm)[, 2], dptval = dpt$dpt, cell_type = cell_cluster_id, norm_cnt=t(as.matrix(sub@assays$integrated@data)))

#df$dptval=max(df$dptval)-df$dptva


p_list=as.list(1:10)

p_list[[1]]=ggplot(df) + geom_point(aes(x = DC1, y = DC2, color = norm_cnt.TBXT),size=0) + theme_classic() + scale_color_gradient2(low='blue',mid='yellow',high='brown3')

pdf(file='Meso diffusioin_12_integrated_1.pdf',width=30,height=30)
plot(p_list[[1]])
dev.off()



p_list[[2]]=ggplot(df) + geom_point(aes(x = DC1, y = DC2, color = norm_cnt.MIXL1),size=0) + theme_classic() + scale_color_gradient2(low='lightblue',mid='lightblue2',high='brown3',midpoint=0.2)

p_list[[3]]=ggplot(df) + geom_point(aes(x = DC1, y = DC2, color = norm_cnt.MESP1),size=0) + theme_classic() + scale_color_gradient2(low='lightblue',mid='lightblue2',high='brown3',midpoint=0.2)

p_list[[4]]=ggplot(df) + geom_point(aes(x = DC1, y = DC2, color = norm_cnt.EOMES),size=0) + theme_classic() + scale_color_gradient2(low='lightblue',mid='lightblue2',high='brown3',midpoint=0.2)

p_list[[5]]=ggplot(df) + geom_point(aes(x = DC1, y = DC2, color = norm_cnt.GATA6),size=0) + theme_classic() + scale_color_gradient2(low='lightblue',mid='lightblue2',high='brown3',midpoint=0.2)

p_list[[6]]=ggplot(df) + geom_point(aes(x = DC1, y = DC2, color = norm_cnt.APLNR),size=0) + theme_classic() + scale_color_gradient2(low='lightblue',mid='lightblue2',high='brown3',midpoint=0.2)

p_list[[7]]=ggplot(df) + geom_point(aes(x = DC1, y = DC2, color = norm_cnt.WNT5B),size=0) + theme_classic() + scale_color_gradient2(low='lightblue',mid='lightblue2',high='brown3',midpoint=0.8)

p_list[[8]]=ggplot(df) + geom_point(aes(x = DC1, y = DC2, color = norm_cnt.CDX2),size=0) + theme_classic() + scale_color_gradient2(low='lightblue',mid='lightblue2',high='brown3',midpoint=0.2)

p_list[[9]]=ggplot(df) + geom_point(aes(x = DC1, y = DC2, color = norm_cnt.LHX1),size=0) + theme_classic() + scale_color_gradient2(low='lightblue',mid='lightblue2',high='brown3',midpoint=0.2)

p_list[[10]]=ggplot(df) + geom_point(aes(x = DC1, y = DC2, color = norm_cnt.PITX2),size=0) + theme_classic() + scale_color_gradient2(low='lightblue',mid='lightblue2',high='brown3',midpoint=0.2)

p_list[[11]]=ggplot(df) + geom_point(aes(x = DC1, y = DC2, color = norm_cnt.PDGFRA),size=0) + theme_classic() + scale_color_gradient2(low='lightblue',mid='lightblue2',high='brown3',midpoint=0.2)

p_list[[12]]=ggplot(df) + geom_point(aes(x = DC1, y = DC2, color = norm_cnt.FOXC1),size=0) + theme_classic() + scale_color_gradient2(low='lightblue',mid='lightblue2',high='brown3',midpoint=0.2)



pdf(file='Meso diffusioin_12_integrated.pdf',width=30,height=30)
ggarrange (plotlist=p_list, ncol = 3, nrow=4)
dev.off()
#############################################################################################################

```



```{r}
# overlap curve for mesoderm lineage 

df=data.frame(DC1 = eigenvectors(dm)[, 1], DC2 = eigenvectors(dm)[, 2], dptval = dpt$dpt, cell_type = cell_cluster_id, norm_cnt=t(as.matrix(Meso_sub@assays$integrated@data)))

# arbitrarily chose split point 
df.PS<- df [df$DC1<0.0034,]

#p_PS_WNT5B<-ggplot(df.PS, aes(dptval,norm_cnt.WNT5B))+ geom_smooth(method = "loess", formula = y ~ x, span=0.3, fill="red", colour="darkred", size=1)
df.ME1<- df [df$DC1>=0.0034&df$DC2>-0.009,]

#meso 1 trajectory
PS.ME1<-rbind(df.PS,df.ME1)

#hist(PS.ME1$dptval,100)

#dptval limit
dff<-PS.ME1[PS.ME1$dptval >= 0.075 & PS.ME1$dptval<= 1.7, ] 

# meso2 trajectory
df.ME2<- df [df$DC1>=0.0034 &df$DC2<=-0.009,]
PS.ME2<-rbind(df.PS,df.ME2)
dfff<-PS.ME2[PS.ME2$dptval >= 0.075 & PS.ME2$dptval<= 1.7, ] 

ggplot(dfff, aes(dptval,norm_cnt.TBXT))+ geom_smooth(method = "loess", formula = y ~ x, span=0.3, fill="red", colour="darkred", size=1)


#plot 
p_list=as.list(1:8)

p1<-ggplot(dff, aes(dptval,norm_cnt.TBXT))+geom_smooth(method = "loess", formula = y ~ x, span=0.3, fill="red", colour="darkred", size=0.1)+ theme_classic()
p_list[[1]]<-p1 + geom_smooth(data=dfff, aes (dptval,norm_cnt.TBXT), method = "loess", formula = y ~ x, span=0.3, fill="blue", colour="darkblue", size=0.1) + theme_classic()

p1<-ggplot(dff, aes(dptval,norm_cnt.MIXL1))+geom_smooth(method = "loess", formula = y ~ x, span=0.3, fill="red", colour="darkred", size=0.1)+ theme_classic()
p_list[[2]]<-p1 + geom_smooth(data=dfff, aes (dptval,norm_cnt.MIXL1), method = "loess", formula = y ~ x, span=0.3, fill="blue", colour="darkblue", size=0.1) + theme_classic()

p1<-ggplot(dff, aes(dptval,norm_cnt.EOMES))+geom_smooth(method = "loess", formula = y ~ x, span=0.3, fill="red", colour="darkred", size=0.1)+ theme_classic()
p_list[[3]]<-p1 + geom_smooth(data=dfff, aes (dptval,norm_cnt.EOMES), method = "loess", formula = y ~ x, span=0.3, fill="blue", colour="darkblue", size=0.1) + theme_classic()

p1<-ggplot(dff, aes(dptval,norm_cnt.APLNR))+geom_smooth(method = "loess", formula = y ~ x, span=0.3, fill="red", colour="darkred", size=0.1)+ theme_classic()
p_list[[4]]<-p1 + geom_smooth(data=dfff, aes (dptval,norm_cnt.APLNR), method = "loess", formula = y ~ x, span=0.3, fill="blue", colour="darkblue", size=0.1) + theme_classic()

p1<-ggplot(dff, aes(dptval,norm_cnt.CDX2))+geom_smooth(method = "loess", formula = y ~ x, span=0.3, fill="red", colour="darkred", size=0.1)+ theme_classic()
p_list[[5]]<-p1 + geom_smooth(data=dfff, aes (dptval,norm_cnt.CDX2), method = "loess", formula = y ~ x, span=0.3, fill="blue", colour="darkblue", size=0.1) + theme_classic()

p1<-ggplot(dff, aes(dptval,norm_cnt.PITX2))+geom_smooth(method = "loess", formula = y ~ x, span=0.3, fill="red", colour="darkred", size=0.1)+ theme_classic()
p_list[[6]]<-p1 + geom_smooth(data=dfff, aes (dptval,norm_cnt.PITX2), method = "loess", formula = y ~ x, span=0.3, fill="blue", colour="darkblue", size=0.1) + theme_classic()

p1<-ggplot(dff, aes(dptval,norm_cnt.GATA6))+geom_smooth(method = "loess", formula = y ~ x, span=0.3, fill="red", colour="darkred", size=0.1)+ theme_classic()
p_list[[7]]<-p1 + geom_smooth(data=dfff, aes (dptval,norm_cnt.GATA6), method = "loess", formula = y ~ x, span=0.3, fill="blue", colour="darkblue", size=0.1) + theme_classic()

p1<-ggplot(dff, aes(dptval,norm_cnt.LHX1))+geom_smooth(method = "loess", formula = y ~ x, span=0.3, fill="red", colour="darkred", size=0.1)+ theme_classic()
p_list[[8]]<-p1 + geom_smooth(data=dfff, aes (dptval,norm_cnt.LHX1), method = "loess", formula = y ~ x, span=0.3, fill="blue", colour="darkblue", size=0.1) + theme_classic()

# p1<-ggplot(dff, aes(dptval,norm_cnt.HOXB6))+geom_smooth(method = "loess", formula = y ~ x, span=0.3, fill="red", colour="darkred", size=0.1)+ theme_classic()
# p_list[[9]]<-p1 + geom_smooth(data=dfff, aes (dptval,norm_cnt.HOXB6), method = "loess", formula = y ~ x, span=0.3, fill="blue", colour="darkblue", size=0.1) + theme_classic()
# 
# p1<-ggplot(dff, aes(dptval,norm_cnt.MESP1))+geom_smooth(method = "loess", formula = y ~ x, span=0.3, fill="red", colour="darkred", size=0.1)+ theme_classic()
# p_list[[10]]<-p1 + geom_smooth(data=dfff, aes (dptval,norm_cnt.MESP1), method = "loess", formula = y ~ x, span=0.3, fill="blue", colour="darkblue", size=0.1) + theme_classic()


pdf(file='Meso_integrated.pdf',width=7.5,height=3)
ggarrange (plotlist=p_list, ncol = 4, nrow=2)
dev.off()

```

```{r}

#Using PGC sub clusters

PGC_sub<-subset(allsamples_PCA_cluster_dims20_res0.5, idents = c("PGCLCs"))

cell_cluster_id=as.character(Idents(Amnioin_sub))

# Using the PCA stored within Seurat object to build diffusion map
pca=Embeddings(Amnioin_sub,reduction='pca') 
dm=DiffusionMap(pca, )

# Create pseudotime ordering and assigns cell to one of three branches
# choose the 10th cell (a cell in cluster 3) as the root
dpt=DPT(dm)

#ref for the colors of clusters:
#new.cluster.ids <- c("ESC","PSLCs","MeLC1","MeLC2","NasAMLC",  "AMLC1", "AMLC2","PGCLCs")
#color<-c('#D39200','#00C19F','#F8766D','#DB72FB','#619CFF','#93AA00','#00B9E3','#00BA38')
#NewOrder = c(3, 1, 5, 0, 4, 6, 7, 2)


# plot pseudotime by diffusion components DC1 vs DC2, coloring the cells by diffusion pseudotime value (dptval)
df=data.frame(DC1 = eigenvectors(dm)[, 1], DC2 = eigenvectors(dm)[, 2], dptval = dpt$dpt, cell_type = cell_cluster_id)

# If needed, reverse the pseudo time because cluster 7 should be the end, not the start of the differentiation. Alternatively, if the root cell happens to be the left-most point in the map, you can find the index of the cell by running: root_index=which(df$DC1==min(df$DC1)), and then rerun dpt: DPT(dm,tips=root_index)

df$dptval=max(df$dptval)-df$dptval

#plot to check the tips points, DPT value 
# plot (dpt)
# plot (dm)

p1=ggplot(df) + geom_point(aes(x = DC1, y = DC2, color = dptval),size=0.001) + scale_color_gradient2(low='red',mid='green',high='blue',midpoint=1.3) + theme_classic()

p2=ggplot(df) + geom_point(aes(x = DC1, y = DC2, color = cell_type),size=0.001) + theme_classic() + scale_color_manual(values=c('#93AA00','#00B9E3','#D39200','#619CFF'))

pdf(file='Amnioin_sub_Diffusion_try.pdf',width=15,height=6)
plot_grid(p1, p2)
dev.off()




```



